### ISSUE TITLE
.post-content img

### ISSUE THREAD

**Issue by MayanMisfit** [cerkit/ghost-cerkit-theme#18]
Maybe change the max width to prevent image from breaking out? on a boxed style like this, it's a fairly bad idea. 
![2016-07-18](https://cloud.githubusercontent.com/assets/20387554/16931320/4fe4ee74-4d38-11e6-9bcf-64fa300bc0e0.png)

**Comment by cerkit** [comment]
I do not understand your suggestion. This theme uses bootstrap, so you'll need to control what's in the panels (post content). Your Twitter embed will need to have its width adjusted (90% might work well).

**Comment by MayanMisfit** [comment]
What your seeing there are two screenshots in a post. 
The problem is that large images break out of the container. 

If the width for the class is currently set to 120% I believe. This is also present in the default Casper. 

Setting it to 100%  will prevent the image from overlapping the post container.

**Comment by cerkit** [comment]
Ah, I see. Thanks for the input. Good catch. I didn't change that css. I agree with you, it shouldn't be this way in this theme considering that all posts are in a Bootstrap panel.

If you'd like to change it and put in a pull request I can merge it. Otherwise, I'll have to look at it later.

You may also be able to add the .img-responsive class to your images to see if that helps (it probably won't considering that screen.css is included after Bootstrap's css.)

The class is defined in [screen.scss](https://github.com/cerkit/ghost-cerkit-theme/blob/master/dev/sass/screen.scss).

**Comment by cerkit** [comment]
Ideally, the images in the posts would use the .img-responsive class [Bootstrap CSS Images](http://www.w3schools.com/bootstrap/bootstrap_ref_css_images.asp) to control the image width within the panel.

**Comment by MayanMisfit** [comment]
Tried submitting the pull request and it error'd out saying i font have access.

**Comment by cerkit** [comment]
Did you fork the project first? [Pull requests on GitHub](https://help.github.com/articles/using-pull-requests/)

**Comment by MayanMisfit** [comment]
ok I think i got it right. bare with me, I'm still learning to use git.

**Comment by cerkit** [comment]
No worries. It took me a while to get the hang of it.

**Comment by cerkit** [comment]
Issue resolved with #19
